name: Prune untagged Docker images

on:
    push:


jobs:
    prune:
        runs-on: ubuntu-latest
        steps:
            - name: Prune
              uses: vlaurin/action-ghcr-prune@v0.6.0
              with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    organization: trufaco
                    container: docker-symfony
                    dry-run: false
                    prune-untagged: true